### ISSUE TITLE
mega.nz link not works

### ISSUE THREAD

**Issue by Karaulov** [jas502n/IDA_Pro_7.2#2]
Please fix this issue. I can't download from paidu. Please make mirror! 🥇

**Comment by BMD4E** [comment]
Here is the link. hurry before they take it down
https://drive.google.com/file/d/1-bQc4K1bJdYkP9ptEANmdd84RwTXB0Vf/view

No password yet, wait until cracker or leaker get the password

**Comment by dartraiden** [comment]
> No password yet, wait until cracker or leaker get the password

Thanks to https://devco.re/blog/2019/06/21/operation-crack-hacking-IDA-Pro-installer-PRNG-from-an-unusual-way-en/

Pass: 7JpT48a7Y2fv

**Comment by jas502n** [comment]
passwd ：7JpT48a7Y2fv


链接：https://pan.baidu.com/s/1UqpaacGafLcPObxWOUIuDQ
提取码：54d4
[image: image.png]

shaoyu zhang <jas502n@gmail.com> 于2019年6月24日周一 上午7:59写道：

> passwd ：7JpT48a7Y2fv
>
> Patrick Schaufuss <ghettopato@gmail.com> 于2019年6月10日周一 下午4:32写道：
>
>> hey,
>> your mega link is down, is there any chance you could reupload it?
>>
>
Alexander <notifications@github.com> 于2019年6月24日周一 上午2:09写道：
